vich_uploader:
    db_driver: orm

    mappings:
        burger_image:
            uri_prefix: /images/burgers
            upload_destination: '%kernel.project_dir%/public/images/burgers'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
