<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client extends User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $telephone;

    public function __construct()
    {

        $this->setRoles(["ROLE_CLIENT"]);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNomComplet(): ?string
    {
        return parent::getNomComplet(); // TODO: Change the autogenerated stub
    }

    public function setNomComplet(string $nomComplet): User
    {
        return parent::setNomComplet($nomComplet); // TODO: Change the autogenerated stub
    }

    public function getEmail(): ?string
    {
        return parent::getEmail(); // TODO: Change the autogenerated stub
    }

    public function setEmail(string $email): User
    {
        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }

    public function getPassword(): ?string
    {
        return parent::getPassword(); // TODO: Change the autogenerated stub
    }

    public function setPassword(string $password): User
    {
        return parent::setPassword($password); // TODO: Change the autogenerated stub
    }

}
